name: Sincronizzazione Oraria Fork

on:
  schedule:
    # Esegue la sincronizzazione ogni ora (al minuto 0)
    - cron: '0 * * * *'
  workflow_dispatch: # Permette l'avvio manuale

jobs:
  sync_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sincronizzazione con Upstream
        env:
          # Questo usa il segreto PAT_TOKEN che hai creato prima
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh repo sync 4kki94/miodbrating --source realbestia1/erdb --force
