name: Sync con Upstream

permissions:
  contents: write
  workflows: write # Aggiungiamo esplicitamente questo

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync Upstream
        env:
          # Usiamo il segreto che hai appena creato
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh repo sync 4kki94/miodbrating --source realbestia1/erdb --force
